Repository onvif/specs, pull requests merged in 2022-06, with the labels that each got.

#218 Add section on media streaming to uplink specification.
  doc/Uplink.xml
Labels: 22.06

#203 Lpr rule configurtaion update
  doc/Analytics.xml
Labels: enhancement, 22.06

#157 Add section for JSON metadata over MQTT
  doc/Analytics.xml
  doc/Core.xml
  wsdl/ver10/events/wsdl/event.wsdl
Labels: enhancement, Analytics, 22.06
